### ISSUE TITLE
Why nothing except renaming works? :)

### ISSUE THREAD

**Issue by OndroV** [TillMacher/apscale_gui#1]
Hi Till,

this tool looks very nice, but so far, I have only achieved all the golden medals for crashing and empty files in PE merging. Not even the Quality Control works.

I see no problem in the installation, settings, nor sample files, do you? I tried fastq.gz files from different runs and projects without any success. It crashes immediately, as if it cant even start the processes.
It would be great if we could fix this, please ;) thanks!

Ondrej

![image](https://user-images.githubusercontent.com/61538402/189491859-620e3bda-475f-4d4d-9782-25d92861dd29.png)
![image](https://user-images.githubusercontent.com/61538402/189492028-efa493bb-e8ac-4dd9-a45e-73eba4463c89.png)
![image](https://user-images.githubusercontent.com/61538402/189492440-bcebe169-ed6d-442e-9820-3366b6350005.png)

**Comment by TillMacher** [comment]
Hi Ondrej,

that's weird. But it must be a local problem since I used the latest version on several other machines.

Could you send me the error when you start e.g. the All-In-One Analysis?

**Comment by OndroV** [comment]
Wow that was fast :) Yes please
For some reason the error is not the same all the time. Maybe because I played with some settings
![image](https://user-images.githubusercontent.com/61538402/189492512-0d0e911a-2a56-49f3-8a68-3a11a85b6f5b.png)
![image](https://user-images.githubusercontent.com/61538402/189492529-67db9dd2-19e4-4578-86ef-5d87d03c4049.png)

**Comment by TillMacher** [comment]
I uploaded some test files in the folder 'https://github.com/TillMacher/apscale_gui/tree/master/_tutorial_data'. Could you try run these with the according Settings.xlsx file?

**Comment by OndroV** [comment]
Thank you, but it still crashes
![image](https://user-images.githubusercontent.com/61538402/189494179-79144920-8551-4c75-a80d-af62f2f680ef.png)

**Comment by TillMacher** [comment]
Mhm ok! Did you try to run the apscale command line version on this machine?

**Comment by OndroV** [comment]
Tried just now and it gives me the same error. So I guess I should create an issue there right?

**Comment by TillMacher** [comment]
Yes please. Then Dominik will fix it :)

**Comment by OndroV** [comment]
Ok, thank you. All the best!
