### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vincentmanz** [TillMacher/apscale_gui#3]
two things : 

1. I have a very very tiny windows, is there a way to calibrate the window of apscale to the screen resolution?

2. If I apply the changes to the parameter for the all in one analysis,  I am getting an error message: 
![Screenshot from 2023-06-13 09-46-54](https://github.com/TillMacher/apscale_gui/assets/15322066/d55452a8-8a7f-4189-a3bc-c63577f55e2c)

thanks !

**Comment by TillMacher** [comment]
I don't have a windows PC myself, but you can resize your screen in your settings. Sadly I cannot do anything about the window size issues on Windows in general.

Regarding the crash: Can you please show me the error message that is printed in the console when clicking "Exit"?

**Comment by vincentmanz** [comment]
I think that's the output: 

`Traceback (most recent call last):
  File "/home/vincent/anaconda3/bin/apscale_gui", line 8, in <module>
    sys.exit(main())
  File "/home/vincent/anaconda3/lib/python3.10/site-packages/apscale_gui/__main__.py", line 348, in main
    settings_dict = load_settings(settings_file)
  File "/home/vincent/anaconda3/lib/python3.10/site-packages/apscale_gui/settings_file.py", line 8, in load_settings
    xl = pd.ExcelFile(file)
  File "/home/vincent/anaconda3/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1500, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
`

**Comment by TillMacher** [comment]
This error usually occurs when you have an .xlsx file opened (e.g., in Excel). Then, a temporary file will be created (e.g., ~$table.xlsx), which causes the crash. Could you please close all files in Excel (or most likely OpenOffice or similar when working on Ubuntu) and try running it again?

Another issue could be that you are using python3 through anaconda, which has caused some issues in the past.
